#!/bin/sh
# complete rebuild of the automake enviroment

#!/bin/sh

rm -rf autom4te.cache

autoscan --force
aclocal --force -I m4
autoheader --force
autoconf --force
automake --force --add-missing
./configure
find . -name "*~" -print -exec rm {} \;

# make clean
# make
# make install
# run program ...
# make uninstall

