#!/bin/sh

################################################################################
# complete rebuild of the make enviroment
################################################################################

rm -rf autom4te.cache
autoscan --force
aclocal --force -I m4
autoheader --force
autoconf --force
automake --force --add-missing
./configure

# make clean
# make
# make install
# run program ...
# make uninstall

