#!/bin/sh

################################################################################
# Complete rebuild of the make enviroment.
################################################################################

rm -rf autom4te.cache
autoscan --force
aclocal --force -I m4
autoheader --force
autoconf --force
automake --force --add-missing
rm -f config.h.in~  

# ./configure [optional args]
# make clean
# make
# make install
# run program ...
# make uninstall

